---
apiVersion: v1
kind: Pod
metadata:
 name: postgre-
 labels:
  type: db
  authour: intelliqit
spec: 
 containers:
  - name: mydb
    image: postgres
    env:
     - name: POSTGRES_ PASSWORD
       value: intelliqit
     - name: POSTGRES_USER
       value: myuser
     - name: POSTGRES_DB
       value: mydb

...
