---
apiVersion: v1
kind: Pod
metadata:
 name: httpd-rc
 labels:
  author: intelliqit
spec: 
 replicas: 3
 template:
  metadata:
   name: httpd_pod
   labels:
    author:
  spec:
   containers:
    - name: myhttpd
      image: httpd
      ports:
       - containerPort: 80
         hostPort: 8080

...

